# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spravkaui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Spravka(object):
    def setupUi(self, Spravka):
        Spravka.setObjectName("Spravka")
        Spravka.resize(653, 567)
        Spravka.setStyleSheet("background-color:rgb(85, 85, 255);")
        self.centralwidget = QtWidgets.QWidget(Spravka)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 10, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 591, 481))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        Spravka.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Spravka)
        self.statusbar.setObjectName("statusbar")
        Spravka.setStatusBar(self.statusbar)

        self.retranslateUi(Spravka)
        QtCore.QMetaObject.connectSlotsByName(Spravka)

    def retranslateUi(self, Spravka):
        _translate = QtCore.QCoreApplication.translate
        Spravka.setWindowTitle(_translate("Spravka", "MainWindow"))
        self.label.setText(_translate("Spravka", "Справка"))
        self.label_2.setText(_translate("Spravka", "<html><head/><body><p><span style=\" font-size:11pt;\">  Данный помощник может выдавать следующую информацию:</span></p><p><span style=\" font-size:11pt;\">  •    О специальностях и направлениях вуза</span></p><p><span style=\" font-size:11pt;\">  •    Об институтах и заведующих кафедры</span></p><p><span style=\" font-size:11pt;\">  •    О ключевых дисциплинах профилей</span></p><p><span style=\" font-size:11pt;\">  •    Об общественных организациях и общежитиях</span></p><p><span style=\" font-size:11pt;\">•    О руководстве вуза</span></p><p><span style=\" font-size:11pt;\">•    Открывает сайт вуза, личный кабинет, мудл и расписание</span></p><p><span style=\" font-size:11pt;\">•    Предоставляет информацию для абитуриентов: </span></p><p><span style=\" font-size:11pt;\">                 1.    Проходные баллы прошлого года</span></p><p><span style=\" font-size:11pt;\">                 2.    Количество бюджетных и платных мест</span></p><p><span style=\" font-size:11pt;\">                 3.    Стоимость обучения</span></p><p><span style=\" font-size:11pt;\">                 4.    Сроки приема документов</span></p><p><span style=\" font-size:11pt;\">                 5.    Лицензия и аккредитация вуза</span></p><p/></body></html>"))
